### ISSUE TITLE
ImportError: No module named 'coinbase_config'

### ISSUE THREAD

**Issue by cyzanfar** [PierreRochard/coinbase-exchange-order-book#4]
I get this error 👆when I do `python2 main.py`

**Comment by PierreRochard** [comment]
I haven't touched this code in a long time, so I'm sure other things will break too. Basically, create a coinbase_config.py file and search the code base to see what constants are imported from that file (API Keys). I'd like to come back to this project at some point (which is why the repo is still up), but don't hold your breath!

**Comment by cyzanfar** [comment]
Awesome thanks for the heads up :)
